name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Determine release type
        run: |
          if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == *"[major]"* ]]; then
            echo "::set-output name=release_type::major"
          elif [[ $(git log --format=%B -n 1 ${{ github.sha }}) == *"[minor]"* ]]; then
            echo "::set-output name=release_type::minor"
          else
            echo "::set-output name=release_type::none"
          fi
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.release.outputs.release_type != 'none' }}
        with:
          files: |
            ./dist/*
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            This is a ${{ steps.release.outputs.release_type }} release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
